### PR TITLE
Re-enable allow-silent-join-quit

### PR DESCRIPTION
**Pull request by REDixxx**
I don't know why it was reverted back :/
But it would be helpful for custom made server

### CODE REVIEW

**Comment by Trophonix** [comment]
It was reverted because people were constantly complaining about joining in vanish because they didn't know about the permission and it counts OPs. e.e

**Comment by HazryG** [comment]
Would there be a way to disable OPs joining in vanish that you could toggle in the essentials code?

**Comment by tjhubz** [comment]
There's a permission for it, essentials.silentjoin.vanish I think.

**Comment by Trophonix** [comment]
I edited the jar so the vanish perm isn't given to ops by default.

**Pull request merged**
